### ISSUE TITLE
BEGIN_OBJECT expected, but met STRING         Scopes: INSIDE_OBJECT>NAME>INSIDE_OBJECT>INSIDE_ARRAY>INSIDE_OBJECT

### ISSUE THREAD

**Issue by DenBond7** [stanfy/gson-xml#14]
Hello. Please, help me.
I have next xml variants.

Variant 1

``` xml
<?xml version="1.0"?>
<main>
  <array_data>
    <element>
      <tag>first</tag>
      <thumbnail_hq>
        <hundred_fifty_square>55/55271.jpg</hundred_fifty_square>
        <three_hundred_square>55271.jpg</three_hundred_square>
      </thumbnail_hq>
    </element>
    <element>
      <tag>second</tag>
      <thumbnail_hq>
        <hundred_fifty_square>55/55277861.jpg</hundred_fifty_square>
        <three_hundred_square>55276871.jpg</three_hundred_square>
      </thumbnail_hq>
    </element>
  </array_data>
</main>
```

Variant 2

``` xml
<?xml version="1.0"?>
<main>
  <array_data>
    <element>
      <tag>first</tag>
      <thumbnail_hq>
        <hundred_fifty_square>55/55271.jpg</hundred_fifty_square>
        <three_hundred_square>55271.jpg</three_hundred_square>
      </thumbnail_hq>
    </element>
    <element>
      <tag>second</tag>
      <thumbnail_hq/>
    </element>
  </array_data>
</main>
```

When I parse 1 variant - all good. But, when I try to parse 2 variant - I receive error: 

``` java
Caused by: java.lang.IllegalStateException: BEGIN_OBJECT expected, but met STRING
        Scopes: INSIDE_OBJECT>NAME>INSIDE_OBJECT>INSIDE_ARRAY>INSIDE_OBJECT
        Closed tags:
        Token: null
        Tokens queue: null
        Values queue: , null
        at com.stanfy.gsonxml.XmlReader.expect(XmlReader.java:143)
        at com.stanfy.gsonxml.XmlReader.beginObject(XmlReader.java:149)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:165)
        ... 25 more
```

I can not work with an empty element.       

This my POJO class.

``` java
public class Element implements Serializable {

  private static final long serialVersionUID = 4286550870315187343L;

  @SerializedName("tag")
  private String tag;

  @SerializedName("thumbnail_hq")
  private Thumb thumbnail_hq;
}
```

``` java


public class Thumb implements Serializable {

  private static final long serialVersionUID = 4286550870315187343L;

  @SerializedName("hundred_fifty_square")
  private String hundred_fifty_square;

  @SerializedName("three_hundred_square")
  private String three_hundred_square;
}
```

**Comment by boomsya** [comment]
today i have the same error
my xml node:
`<FAX xsi:nil = "true"/>`

does someone have ideas how to parse this nodes?
